### ISSUE TITLE
ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by dev-goalz** [Dutchosintguy/OSINT-timeline#2]
Hi!

I've cloned the repo, installed the dependencies but running `python OSINT_timeline.py` gives this error instantly:

```
Traceback (most recent call last):
  File "/home/x/Scripts/OSINT-timeline/OSINT_timeline.py", line 2, in <module>
    import pandas as pd
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/x/Scripts/OSINT-timeline/lib/python3.12/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

```
Requirement already satisfied: Flask==2.3.3 in ./lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: pandas==2.0.3 in ./lib/python3.12/site-packages (from -r requirements.txt (line 2)) (2.0.3)
Requirement already satisfied: matplotlib==3.7.2 in ./lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.7.2)
Requirement already satisfied: fpdf==1.7.2 in ./lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.7.2)
Requirement already satisfied: plotly==5.15.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 5)) (5.15.0)
Requirement already satisfied: networkx==3.1 in ./lib/python3.12/site-packages (from -r requirements.txt (line 6)) (3.1)
Requirement already satisfied: Werkzeug>=2.3.7 in ./lib/python3.12/site-packages (from Flask==2.3.3->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: Jinja2>=3.1.2 in ./lib/python3.12/site-packages (from Flask==2.3.3->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in ./lib/python3.12/site-packages (from Flask==2.3.3->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in ./lib/python3.12/site-packages (from Flask==2.3.3->-r requirements.txt (line 1)) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in ./lib/python3.12/site-packages (from Flask==2.3.3->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas==2.0.3->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas==2.0.3->-r requirements.txt (line 2)) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in ./lib/python3.12/site-packages (from pandas==2.0.3->-r requirements.txt (line 2)) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in ./lib/python3.12/site-packages (from pandas==2.0.3->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: contourpy>=1.0.1 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (24.1)
Requirement already satisfied: pillow>=6.2.0 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (10.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in ./lib/python3.12/site-packages (from matplotlib==3.7.2->-r requirements.txt (line 3)) (3.0.9)
Requirement already satisfied: tenacity>=6.2.0 in ./lib/python3.12/site-packages (from plotly==5.15.0->-r requirements.txt (line 5)) (9.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from Jinja2>=3.1.2->Flask==2.3.3->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.0.3->-r requirements.txt (line 2)) (1.16.0)
```

**Comment by dev-goalz** [comment]
Seems the problem was explained here:
[](https://stackoverflow.com/a/78641304)

Downgrading to `pip install numpy==1.26.4` seems to work, although you might be able to get compatible versions in the requirements?
